<?php
	// 1.0.8 Added 'SR_PREVIEW'.
	if(!defined('ABSPATH')) exit; 	// Exit if accessed directly

    /* set defalt setting datas */
	$db_get = Array(
		'SR_DISPLAY'  => '1',
		'SR_PREVIEW'  => '1',
		'SR_CHECK'    => '1',
		'SR_COMMENT1' => '<!-- Sample : myface-3 --><style type="text/css"><!-- table.samurai1 {background-repeat:no-repeat; table-layout:fixed; margin-left:auto; margin-right:auto;}.samurai2 {border:none;}td.samurai3{text-align:center; vertical-align:middle; padding:1em; font-size:14px; line-height:1.5em;} --></style><table style="height:121px;width:320px;" class="samurai1 samurai2" background="' . plugins_url('img/myface-3.png',__FILE__) . '"><tbody><tr class="samurai2"><td width="52%" class="samurai2"></td><td width="48%" class="samurai2 samurai3">Hi !<br>Welcome you.<br>Thank you for your comment.</td></tr></tbody></table><p>    僕はサイト管理人です！</br>    I am a site administrator!</p>',
		'SR_COMMENT2' => '<!-- Sample : ukiyoe-0101-1 --><style type="text/css"><!-- table.samurai1 {background-repeat:no-repeat; table-layout:fixed; margin-left:auto; margin-right:auto;}.samurai2 {border:none;}td.samurai3{text-align:center; vertical-align:middle; padding:1em; font-size:14px; line-height:1.5em;} --></style><table style="height:149px;width:320px" class="samurai1 samurai2" background="' . plugins_url('img/ukiyoe-0101-1.png',__FILE__) . '"><tbody><tr class="samurai2"><td width="35%" class="samurai2"></td><td width="65%" class="samurai2 samurai3">Hi !<br>Welcome you.</td></tr></tbody></table>',
		'SR_COMMENT3' => '<!-- Sample : ukiyoe-0201-1 --><style type="text/css"><!-- table.samurai1 {background-repeat:no-repeat; table-layout:fixed; margin-left:auto; margin-right:auto;}.samurai2 {border:none;}td.samurai3{text-align:center; vertical-align:middle; padding:1em; font-size:14px; line-height:1.2em; color:blue;} --></style><table style="height:116px;width:320px;" class="samurai1 samurai2" background="' . plugins_url('img/ukiyoe-0201-1.png',__FILE__) . '"><tbody><tr class="samurai2"><td width="34%" class="samurai2"></td><td width="66%" class="samurai2 samurai3">Hi !<br>Welcome you.<br>Please give me </br>your comment.</br> </br> </td></tr></tbody></table>',
		'SR_COMMENT4' => '<!-- Sample : ukiyoe-0301-1 --><style type="text/css"><!-- table.samurai1 {background-repeat:no-repeat; table-layout:fixed; margin-left:auto; margin-right:auto;}.samurai2 {border:none;}td.samurai3{text-align:center; vertical-align:middle; padding:1em; font-size:14px; line-height:1.2em; color:blue;} --></style><table style="height:138px;width:320px;" class="samurai1 samurai2" background="' . plugins_url('img/ukiyoe-0301-1.png',__FILE__) . '"><tbody><tr class="samurai2"><td width="50%" class="samurai2 samurai3">Hi !<br>Welcome you.<br>Please give me<br>your comment.</td><td width="50%" class="samurai2"></td></tr></tbody></table>',
		'SR_COMMENT5' => '<!-- Sample : ukiyoe-0401-1 --><style type="text/css"><!-- table.samurai1 {background-repeat:no-repeat; table-layout:fixed; margin-left:auto; margin-right:auto;}.samurai2 {border:none;}td.samurai3{text-align:center; vertical-align:middle; padding:1em; font-size:14px; line-height:1.2em; color:blue;} --></style><table style="height:164px;width:320px;" class="samurai1 samurai2" background="' . plugins_url('img/ukiyoe-0401-1.png',__FILE__) . '"><tbody><tr class="samurai2"><td width="52%" class="samurai2 samurai3">Hi !<br>Welcome you.<br>Please give me<br>your comment.<br>  <br>  <br></td><td width="48%" class="samurai2"></td></tr></tbody></table>',
		'SR_COMMENT6' => '<!-- Sample : ukiyoe-0601-1 --><style type="text/css"><!-- table.samurai1 {background-repeat:no-repeat; table-layout:fixed; margin-left:auto; margin-right:auto;}.samurai2 {border:none;}td.samurai3{text-align:center; vertical-align:middle; padding:1em; font-size:14px; line-height:1.2em; color:black;} --></style><table style="height:200px;width:320px;" class="samurai1 samurai2" background="' . plugins_url('img/ukiyoe-0601-1.png',__FILE__) . '"><tbody><tr class="samurai2"><td width="48%" class="samurai2"></td><td width="52%" class="samurai2 samurai3">Hi !<br>Welcome you.<br>Please give me<br>your comment.<br>  <br>  <br>  <br></td></tr></tbody></table>',
		'SR_COMMENT7' => '<!-- Sample : ukiyoe-0701-1 --><style type="text/css"><!-- table.samurai1 {background-repeat:no-repeat; table-layout:fixed; margin-left:auto; margin-right:auto;}.samurai2 {border:none;}td.samurai3{font-size:13px; text-align:center; vertical-align: middle; padding:1em; border:none; line-height:1.2em; color:black;} --></style><table style="height:220px;width:325px;" class="samurai1 samurai2" background="' . plugins_url('img/ukiyoe-0701-1.png',__FILE__) . '"><tr style="height:115px;"><td style="width:58%;" class="samurai2"></td></tr><tr style="height:105px;"><td rowspan="2" style="width:42%;" class="samurai2 samurai3">Hi !<br>Welcome you.<br>Please give me<br>your comment.</td><td class="samurai2"></td></tr></table>',
		'SR_COUNT'    => '7',       /* data count */
		'SR_UPDATE'   => getdate() 	/* Update date */
	);
?>